test: add intentional fail step to fail chaining workflow

diff --git a/.github/workflows/deploy-after-tests.yml b/.github/workflows/deploy-after-tests.yml
--- a/.github/workflows/deploy-after-tests.yml
+++ b/.github/workflows/deploy-after-tests.yml
@@ -20,4 +20,7 @@ jobs:
 
       - name: Fail message if tests failed
         if: ${{ github.event.workflow_run.conclusion != 'success' }}
-        run: echo "Tests failed. Skipping deployment."
+        run: | 
+          echo "Tests failed. Skipping deployment."
+          exit 1 
+
