fix: remove intentional failure and restore pipeline

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -25,5 +25,5 @@ jobs:
       - name: Print the Runner's Operating system
         run: echo "Running on ${{ runner.os }}"
 
-      - name: Intentional Failure Step
-        run: exit 1
+ #    - name: Intentional Failure Step
+ #      run: exit 1
